// ===== MOCK DATA =====
// Mirrors the exact AirportStatus schema from the backend.
// This is snapshot 0 — a calm state before the disruption.

const base = new Date('2026-07-24T08:00:00Z');
const t = (m) => new Date(base.getTime() + m * 60000).toISOString();

export const MOCK_SNAPSHOTS = [
  // === TICK 0: Flights arriving, gates being assigned ===
  {
    current_tick: 0,
    flights: {
      'AI101': { flight_id:'AI101', airline:'Air India', aircraft_type:'WIDE_BODY', scheduled_arrival:t(0), scheduled_departure:t(90), actual_arrival:t(2), actual_departure:null, status:'LANDED', assigned_gate:'G1', assigned_crew:['C001','C002','C003'], turnaround_time:90, is_delayed:false },
      'AI102': { flight_id:'AI102', airline:'Air India', aircraft_type:'NARROW_BODY', scheduled_arrival:t(2), scheduled_departure:t(52), actual_arrival:t(5), actual_departure:null, status:'AT_GATE', assigned_gate:'G2', assigned_crew:['C004','C005'], turnaround_time:45, is_delayed:true },
      'UK303': { flight_id:'UK303', airline:'Vistara', aircraft_type:'NARROW_BODY', scheduled_arrival:t(5), scheduled_departure:t(55), actual_arrival:t(5), actual_departure:null, status:'AT_GATE', assigned_gate:'G3', assigned_crew:['C006'], turnaround_time:45, is_delayed:false },
      'SG404': { flight_id:'SG404', airline:'SpiceJet', aircraft_type:'NARROW_BODY', scheduled_arrival:t(8), scheduled_departure:t(58), actual_arrival:null, actual_departure:null, status:'IN_AIR', assigned_gate:null, assigned_crew:[], turnaround_time:40, is_delayed:false },
      'G8505': { flight_id:'G8505', airline:'GoFirst', aircraft_type:'NARROW_BODY', scheduled_arrival:t(10), scheduled_departure:t(60), actual_arrival:null, actual_departure:null, status:'IN_AIR', assigned_gate:null, assigned_crew:[], turnaround_time:40, is_delayed:false },
      'AI603': { flight_id:'AI603', airline:'Air India Express', aircraft_type:'WIDE_BODY', scheduled_arrival:t(45), scheduled_departure:t(145), actual_arrival:null, actual_departure:null, status:'SCHEDULED', assigned_gate:null, assigned_crew:[], turnaround_time:95, is_delayed:false },
      'IX700': { flight_id:'IX700', airline:'Air India Express', aircraft_type:'NARROW_BODY', scheduled_arrival:t(60), scheduled_departure:t(110), actual_arrival:null, actual_departure:null, status:'SCHEDULED', assigned_gate:null, assigned_crew:[], turnaround_time:45, is_delayed:false },
      '6E801': { flight_id:'6E801', airline:'IndiGo', aircraft_type:'NARROW_BODY', scheduled_arrival:t(30), scheduled_departure:t(75), actual_arrival:null, actual_departure:null, status:'SCHEDULED', assigned_gate:null, assigned_crew:[], turnaround_time:42, is_delayed:false },
      '6E802': { flight_id:'6E802', airline:'IndiGo', aircraft_type:'NARROW_BODY', scheduled_arrival:t(35), scheduled_departure:t(80), actual_arrival:null, actual_departure:null, status:'SCHEDULED', assigned_gate:null, assigned_crew:[], turnaround_time:42, is_delayed:false },
      'QP901': { flight_id:'QP901', airline:'Akasa Air', aircraft_type:'NARROW_BODY', scheduled_arrival:t(55), scheduled_departure:t(100), actual_arrival:null, actual_departure:null, status:'SCHEDULED', assigned_gate:null, assigned_crew:[], turnaround_time:38, is_delayed:false },
    },
    gates: {
      'G1': { gate_id:'G1', supports_wide_body:true,  gate_status:'OCCUPIED',   assigned_flight:'AI101' },
      'G2': { gate_id:'G2', supports_wide_body:false, gate_status:'OCCUPIED',   assigned_flight:'AI102' },
      'G3': { gate_id:'G3', supports_wide_body:false, gate_status:'OCCUPIED',   assigned_flight:'UK303' },
      'G4': { gate_id:'G4', supports_wide_body:false, gate_status:'OPEN',       assigned_flight:null },
      'G5': { gate_id:'G5', supports_wide_body:true,  gate_status:'OPEN',       assigned_flight:null },
      'G6': { gate_id:'G6', supports_wide_body:false, gate_status:'OPEN',       assigned_flight:null },
      'G7': { gate_id:'G7', supports_wide_body:false, gate_status:'OPEN',       assigned_flight:null },
      'G8': { gate_id:'G8', supports_wide_body:true,  gate_status:'OPEN',       assigned_flight:null },
      'G9': { gate_id:'G9', supports_wide_body:false, gate_status:'OPEN',       assigned_flight:null },
      'G10':{ gate_id:'G10',supports_wide_body:false, gate_status:'OPEN',       assigned_flight:null },
    },
    crew: {
      'C001':{ crew_id:'C001', role:'BAGGAGE',  available:false, assigned_flight:'AI101', shift_minutes_remaining:360 },
      'C002':{ crew_id:'C002', role:'PUSHBACK', available:false, assigned_flight:'AI101', shift_minutes_remaining:320 },
      'C003':{ crew_id:'C003', role:'CLEANING', available:false, assigned_flight:'AI101', shift_minutes_remaining:290 },
      'C004':{ crew_id:'C004', role:'BAGGAGE',  available:false, assigned_flight:'AI102', shift_minutes_remaining:410 },
      'C005':{ crew_id:'C005', role:'PUSHBACK', available:false, assigned_flight:'AI102', shift_minutes_remaining:380 },
      'C006':{ crew_id:'C006', role:'CLEANING', available:false, assigned_flight:'UK303', shift_minutes_remaining:340 },
      'C007':{ crew_id:'C007', role:'BAGGAGE',  available:true,  assigned_flight:null, shift_minutes_remaining:480 },
      'C008':{ crew_id:'C008', role:'PUSHBACK', available:true,  assigned_flight:null, shift_minutes_remaining:460 },
      'C009':{ crew_id:'C009', role:'CLEANING', available:true,  assigned_flight:null, shift_minutes_remaining:440 },
      'C010':{ crew_id:'C010', role:'BAGGAGE',  available:true,  assigned_flight:null, shift_minutes_remaining:500 },
      'C011':{ crew_id:'C011', role:'PUSHBACK', available:true,  assigned_flight:null, shift_minutes_remaining:390 },
      'C012':{ crew_id:'C012', role:'CLEANING', available:true,  assigned_flight:null, shift_minutes_remaining:350 },
    },
    open_disruptions: [],
    open_conflicts: [],
    decision_log: [
      { tick:0, agent_id:'gate_agent', action:'gate_assignment', detail:'Assigned AI101 (Wide Body) to Gate G1 — best fit for wide-body aircraft with longest remaining turnaround.', affected_flights:['AI101'] },
      { tick:0, agent_id:'gate_agent', action:'gate_assignment', detail:'Assigned AI102 (Narrow Body) to Gate G2 — narrow-body fit, efficient use of compact gate.', affected_flights:['AI102'] },
      { tick:0, agent_id:'gate_agent', action:'gate_assignment', detail:'Assigned UK303 (Narrow Body) to Gate G3 — standard assignment, no conflicts detected.', affected_flights:['UK303'] },
      { tick:0, agent_id:'crew_agent', action:'crew_assignment', detail:'Assigned crew C001 (Baggage), C002 (Pushback), C003 (Cleaning) to AI101 — all roles covered, shift hours sufficient.', affected_flights:['AI101'] },
      { tick:0, agent_id:'crew_agent', action:'crew_assignment', detail:'Assigned crew C004 (Baggage), C005 (Pushback) to AI102 — partial assignment, awaiting cleaning crew availability.', affected_flights:['AI102'] },
      { tick:0, agent_id:'ats_agent', action:'delay_flag', detail:'AI102 actual arrival +3 min vs scheduled — flagged as delayed. Cascade risk LOW for current gate assignments.', affected_flights:['AI102'] },
    ],
  },

  // === TICK 5: SG404 and G8505 land, disruption approaches ===
  {
    current_tick: 5,
    flights: {
      'AI101': { flight_id:'AI101', airline:'Air India', aircraft_type:'WIDE_BODY', scheduled_arrival:t(0), scheduled_departure:t(90), actual_arrival:t(2), actual_departure:null, status:'AT_GATE', assigned_gate:'G1', assigned_crew:['C001','C002','C003'], turnaround_time:90, is_delayed:false },
      'AI102': { flight_id:'AI102', airline:'Air India', aircraft_type:'NARROW_BODY', scheduled_arrival:t(2), scheduled_departure:t(52), actual_arrival:t(5), actual_departure:null, status:'AT_GATE', assigned_gate:'G2', assigned_crew:['C004','C005','C006'], turnaround_time:45, is_delayed:true },
      'UK303': { flight_id:'UK303', airline:'Vistara', aircraft_type:'NARROW_BODY', scheduled_arrival:t(5), scheduled_departure:t(55), actual_arrival:t(5), actual_departure:null, status:'AT_GATE', assigned_gate:'G3', assigned_crew:['C007'], turnaround_time:45, is_delayed:false },
      'SG404': { flight_id:'SG404', airline:'SpiceJet', aircraft_type:'NARROW_BODY', scheduled_arrival:t(8), scheduled_departure:t(58), actual_arrival:t(9), actual_departure:null, status:'AT_GATE', assigned_gate:'G4', assigned_crew:['C008','C009'], turnaround_time:40, is_delayed:true },
      'G8505': { flight_id:'G8505', airline:'GoFirst', aircraft_type:'NARROW_BODY', scheduled_arrival:t(10), scheduled_departure:t(60), actual_arrival:t(11), actual_departure:null, status:'LANDED', assigned_gate:null, assigned_crew:[], turnaround_time:40, is_delayed:false },
      'AI603': { flight_id:'AI603', airline:'Air India Express', aircraft_type:'WIDE_BODY', scheduled_arrival:t(45), scheduled_departure:t(145), actual_arrival:null, actual_departure:null, status:'SCHEDULED', assigned_gate:null, assigned_crew:[], turnaround_time:95, is_delayed:false },
      'IX700': { flight_id:'IX700', airline:'Air India Express', aircraft_type:'NARROW_BODY', scheduled_arrival:t(60), scheduled_departure:t(110), actual_arrival:null, actual_departure:null, status:'SCHEDULED', assigned_gate:null, assigned_crew:[], turnaround_time:45, is_delayed:false },
      '6E801': { flight_id:'6E801', airline:'IndiGo', aircraft_type:'NARROW_BODY', scheduled_arrival:t(30), scheduled_departure:t(75), actual_arrival:null, actual_departure:null, status:'SCHEDULED', assigned_gate:null, assigned_crew:[], turnaround_time:42, is_delayed:false },
      '6E802': { flight_id:'6E802', airline:'IndiGo', aircraft_type:'NARROW_BODY', scheduled_arrival:t(35), scheduled_departure:t(80), actual_arrival:null, actual_departure:null, status:'SCHEDULED', assigned_gate:null, assigned_crew:[], turnaround_time:42, is_delayed:false },
      'QP901': { flight_id:'QP901', airline:'Akasa Air', aircraft_type:'NARROW_BODY', scheduled_arrival:t(55), scheduled_departure:t(100), actual_arrival:null, actual_departure:null, status:'SCHEDULED', assigned_gate:null, assigned_crew:[], turnaround_time:38, is_delayed:false },
    },
    gates: {
      'G1': { gate_id:'G1', supports_wide_body:true,  gate_status:'OCCUPIED',   assigned_flight:'AI101' },
      'G2': { gate_id:'G2', supports_wide_body:false, gate_status:'OCCUPIED',   assigned_flight:'AI102' },
      'G3': { gate_id:'G3', supports_wide_body:false, gate_status:'OCCUPIED',   assigned_flight:'UK303' },
      'G4': { gate_id:'G4', supports_wide_body:false, gate_status:'OCCUPIED',   assigned_flight:'SG404' },
      'G5': { gate_id:'G5', supports_wide_body:true,  gate_status:'OPEN',       assigned_flight:null },
      'G6': { gate_id:'G6', supports_wide_body:false, gate_status:'OPEN',       assigned_flight:null },
      'G7': { gate_id:'G7', supports_wide_body:false, gate_status:'OPEN',       assigned_flight:null },
      'G8': { gate_id:'G8', supports_wide_body:true,  gate_status:'OPEN',       assigned_flight:null },
      'G9': { gate_id:'G9', supports_wide_body:false, gate_status:'OPEN',       assigned_flight:null },
      'G10':{ gate_id:'G10',supports_wide_body:false, gate_status:'OPEN',       assigned_flight:null },
    },
    crew: {
      'C001':{ crew_id:'C001', role:'BAGGAGE',  available:false, assigned_flight:'AI101', shift_minutes_remaining:355 },
      'C002':{ crew_id:'C002', role:'PUSHBACK', available:false, assigned_flight:'AI101', shift_minutes_remaining:315 },
      'C003':{ crew_id:'C003', role:'CLEANING', available:false, assigned_flight:'AI101', shift_minutes_remaining:285 },
      'C004':{ crew_id:'C004', role:'BAGGAGE',  available:false, assigned_flight:'AI102', shift_minutes_remaining:405 },
      'C005':{ crew_id:'C005', role:'PUSHBACK', available:false, assigned_flight:'AI102', shift_minutes_remaining:375 },
      'C006':{ crew_id:'C006', role:'CLEANING', available:false, assigned_flight:'AI102', shift_minutes_remaining:335 },
      'C007':{ crew_id:'C007', role:'BAGGAGE',  available:false, assigned_flight:'UK303', shift_minutes_remaining:335 },
      'C008':{ crew_id:'C008', role:'PUSHBACK', available:false, assigned_flight:'SG404', shift_minutes_remaining:455 },
      'C009':{ crew_id:'C009', role:'CLEANING', available:false, assigned_flight:'SG404', shift_minutes_remaining:435 },
      'C010':{ crew_id:'C010', role:'BAGGAGE',  available:true,  assigned_flight:null, shift_minutes_remaining:495 },
      'C011':{ crew_id:'C011', role:'PUSHBACK', available:true,  assigned_flight:null, shift_minutes_remaining:385 },
      'C012':{ crew_id:'C012', role:'CLEANING', available:true,  assigned_flight:null, shift_minutes_remaining:345 },
    },
    open_disruptions: [],
    open_conflicts: [],
    decision_log: [
      { tick:0, agent_id:'gate_agent', action:'gate_assignment', detail:'Assigned AI101 (Wide Body) to Gate G1 — best fit for wide-body aircraft with longest remaining turnaround.', affected_flights:['AI101'] },
      { tick:0, agent_id:'gate_agent', action:'gate_assignment', detail:'Assigned AI102 to Gate G2 — narrow-body fit, efficient use of compact gate.', affected_flights:['AI102'] },
      { tick:0, agent_id:'gate_agent', action:'gate_assignment', detail:'Assigned UK303 (Narrow Body) to Gate G3 — standard assignment, no conflicts detected.', affected_flights:['UK303'] },
      { tick:0, agent_id:'crew_agent', action:'crew_assignment', detail:'Assigned crew C001, C002, C003 to AI101 — all roles covered.', affected_flights:['AI101'] },
      { tick:0, agent_id:'crew_agent', action:'crew_assignment', detail:'Assigned crew C004, C005, C006 to AI102 — all roles covered.', affected_flights:['AI102'] },
      { tick:0, agent_id:'ats_agent', action:'delay_flag', detail:'AI102 actual arrival +3 min — flagged as delayed. Cascade risk LOW.', affected_flights:['AI102'] },
      { tick:5, agent_id:'gate_agent', action:'gate_assignment', detail:'Assigned SG404 to Gate G4 — only available narrow-body gate at this time.', affected_flights:['SG404'] },
      { tick:5, agent_id:'crew_agent', action:'crew_assignment', detail:'Assigned crew C008, C009 to SG404. C007 assigned to UK303 (Baggage only — Pushback pending).', affected_flights:['SG404','UK303'] },
      { tick:5, agent_id:'ats_agent', action:'delay_flag', detail:'SG404 actual arrival +1 min — minor delay. Gate G4 turnaround window adequate.', affected_flights:['SG404'] },
    ],
  },

  // === TICK 5 (continued): WEATHER DISRUPTION FIRES ===
  {
    current_tick: 5,
    flights: {
      'AI101': { flight_id:'AI101', airline:'Air India', aircraft_type:'WIDE_BODY', scheduled_arrival:t(0), scheduled_departure:t(90), actual_arrival:t(2), actual_departure:null, status:'AT_GATE', assigned_gate:'G1', assigned_crew:['C001','C002','C003'], turnaround_time:90, is_delayed:false },
      'AI102': { flight_id:'AI102', airline:'Air India', aircraft_type:'NARROW_BODY', scheduled_arrival:t(2), scheduled_departure:t(52), actual_arrival:t(5), actual_departure:null, status:'AT_GATE', assigned_gate:'G2', assigned_crew:['C004','C005','C006'], turnaround_time:45, is_delayed:true },
      'UK303': { flight_id:'UK303', airline:'Vistara', aircraft_type:'NARROW_BODY', scheduled_arrival:t(5), scheduled_departure:t(55), actual_arrival:t(5), actual_departure:null, status:'AT_GATE', assigned_gate:'G3', assigned_crew:['C007'], turnaround_time:45, is_delayed:false },
      'SG404': { flight_id:'SG404', airline:'SpiceJet', aircraft_type:'NARROW_BODY', scheduled_arrival:t(8), scheduled_departure:t(58), actual_arrival:t(9), actual_departure:null, status:'AT_GATE', assigned_gate:'G4', assigned_crew:['C008','C009'], turnaround_time:40, is_delayed:true },
      'G8505': { flight_id:'G8505', airline:'GoFirst', aircraft_type:'NARROW_BODY', scheduled_arrival:t(10), scheduled_departure:t(60), actual_arrival:t(11), actual_departure:null, status:'AT_GATE', assigned_gate:'G5', assigned_crew:['C010','C011'], turnaround_time:40, is_delayed:false },
      'AI603': { flight_id:'AI603', airline:'Air India Express', aircraft_type:'WIDE_BODY', scheduled_arrival:t(45), scheduled_departure:t(145), actual_arrival:null, actual_departure:null, status:'SCHEDULED', assigned_gate:null, assigned_crew:[], turnaround_time:95, is_delayed:false },
      'IX700': { flight_id:'IX700', airline:'Air India Express', aircraft_type:'NARROW_BODY', scheduled_arrival:t(60), scheduled_departure:t(110), actual_arrival:null, actual_departure:null, status:'SCHEDULED', assigned_gate:null, assigned_crew:[], turnaround_time:45, is_delayed:false },
      '6E801': { flight_id:'6E801', airline:'IndiGo', aircraft_type:'NARROW_BODY', scheduled_arrival:t(30), scheduled_departure:t(75), actual_arrival:null, actual_departure:null, status:'SCHEDULED', assigned_gate:null, assigned_crew:[], turnaround_time:42, is_delayed:false },
      '6E802': { flight_id:'6E802', airline:'IndiGo', aircraft_type:'NARROW_BODY', scheduled_arrival:t(35), scheduled_departure:t(80), actual_arrival:null, actual_departure:null, status:'SCHEDULED', assigned_gate:null, assigned_crew:[], turnaround_time:42, is_delayed:false },
      'QP901': { flight_id:'QP901', airline:'Akasa Air', aircraft_type:'NARROW_BODY', scheduled_arrival:t(55), scheduled_departure:t(100), actual_arrival:null, actual_departure:null, status:'SCHEDULED', assigned_gate:null, assigned_crew:[], turnaround_time:38, is_delayed:false },
    },
    gates: {
      'G1': { gate_id:'G1', supports_wide_body:true,  gate_status:'OCCUPIED',   assigned_flight:'AI101' },
      'G2': { gate_id:'G2', supports_wide_body:false, gate_status:'OCCUPIED',   assigned_flight:'AI102' },
      'G3': { gate_id:'G3', supports_wide_body:false, gate_status:'OCCUPIED',   assigned_flight:'UK303' },
      'G4': { gate_id:'G4', supports_wide_body:false, gate_status:'OCCUPIED',   assigned_flight:'SG404' },
      'G5': { gate_id:'G5', supports_wide_body:true,  gate_status:'OCCUPIED',   assigned_flight:'G8505' },
      'G6': { gate_id:'G6', supports_wide_body:false, gate_status:'OPEN',       assigned_flight:null },
      'G7': { gate_id:'G7', supports_wide_body:false, gate_status:'OPEN',       assigned_flight:null },
      'G8': { gate_id:'G8', supports_wide_body:true,  gate_status:'UNAVAILABLE',assigned_flight:null },
      'G9': { gate_id:'G9', supports_wide_body:false, gate_status:'OPEN',       assigned_flight:null },
      'G10':{ gate_id:'G10',supports_wide_body:false, gate_status:'OPEN',       assigned_flight:null },
    },
    crew: {
      'C001':{ crew_id:'C001', role:'BAGGAGE',  available:false, assigned_flight:'AI101', shift_minutes_remaining:350 },
      'C002':{ crew_id:'C002', role:'PUSHBACK', available:false, assigned_flight:'AI101', shift_minutes_remaining:310 },
      'C003':{ crew_id:'C003', role:'CLEANING', available:false, assigned_flight:'AI101', shift_minutes_remaining:280 },
      'C004':{ crew_id:'C004', role:'BAGGAGE',  available:false, assigned_flight:'AI102', shift_minutes_remaining:400 },
      'C005':{ crew_id:'C005', role:'PUSHBACK', available:false, assigned_flight:'AI102', shift_minutes_remaining:370 },
      'C006':{ crew_id:'C006', role:'CLEANING', available:false, assigned_flight:'AI102', shift_minutes_remaining:330 },
      'C007':{ crew_id:'C007', role:'BAGGAGE',  available:false, assigned_flight:'UK303', shift_minutes_remaining:330 },
      'C008':{ crew_id:'C008', role:'PUSHBACK', available:false, assigned_flight:'SG404', shift_minutes_remaining:450 },
      'C009':{ crew_id:'C009', role:'CLEANING', available:false, assigned_flight:'SG404', shift_minutes_remaining:430 },
      'C010':{ crew_id:'C010', role:'BAGGAGE',  available:false, assigned_flight:'G8505', shift_minutes_remaining:490 },
      'C011':{ crew_id:'C011', role:'PUSHBACK', available:false, assigned_flight:'G8505', shift_minutes_remaining:380 },
      'C012':{ crew_id:'C012', role:'CLEANING', available:true,  assigned_flight:null, shift_minutes_remaining:340 },
    },
    open_disruptions: [
      {
        event_id: 'DIS-WEATHER-001',
        disruption_type: 'WEATHER',
        trigger_time: t(25),
        severity: 4,
        disruption_description: 'Severe thunderstorm cell moving through approach corridor. Wind shear reported on runway 27L. All inbound traffic on holding pattern. Gates G1–G5 affected — extended occupancy expected.',
        affected_flights: ['AI101','AI102','UK303','SG404','G8505'],
        resolved: false,
      }
    ],
    open_conflicts: [
      {
        conflict_id: 'CON-001',
        agent_id: 'gate_agent',
        conflict_description: 'Gate G5 assigned to G8505 (Wide Body slot), but AI603 (Wide Body, arriving T+45) has no remaining wide-body-capable gate available. G8 is UNAVAILABLE. Conflict: insufficient wide-body capacity.',
        resolved: false,
        affected_flights: ['G8505','AI603'],
      }
    ],
    decision_log: [
      { tick:0, agent_id:'gate_agent', action:'gate_assignment', detail:'Assigned AI101 (Wide Body) to Gate G1 — best fit.', affected_flights:['AI101'] },
      { tick:0, agent_id:'gate_agent', action:'gate_assignment', detail:'Assigned AI102 to Gate G2 — narrow-body fit.', affected_flights:['AI102'] },
      { tick:0, agent_id:'gate_agent', action:'gate_assignment', detail:'Assigned UK303 to Gate G3 — standard assignment.', affected_flights:['UK303'] },
      { tick:0, agent_id:'crew_agent', action:'crew_assignment', detail:'Assigned crew C001, C002, C003 to AI101.', affected_flights:['AI101'] },
      { tick:0, agent_id:'crew_agent', action:'crew_assignment', detail:'Assigned crew C004, C005, C006 to AI102.', affected_flights:['AI102'] },
      { tick:0, agent_id:'ats_agent', action:'delay_flag', detail:'AI102 actual arrival +3 min — flagged as delayed. Cascade risk LOW.', affected_flights:['AI102'] },
      { tick:5, agent_id:'gate_agent', action:'gate_assignment', detail:'Assigned SG404 to Gate G4.', affected_flights:['SG404'] },
      { tick:5, agent_id:'gate_agent', action:'gate_assignment', detail:'Assigned G8505 to Gate G5 (wide-body slot). NOTE: This exhausts wide-body capacity — G8 marked UNAVAILABLE due to emergency safety inspection.', affected_flights:['G8505'] },
      { tick:5, agent_id:'disruption_agent', action:'disruption_triggered', detail:'🌩 DIS-WEATHER-001 INJECTED — Severity LEVEL_4 thunderstorm event. 5 flights affected in bottleneck cluster. Escalating to Orchestrator for replanning.', affected_flights:['AI101','AI102','UK303','SG404','G8505'] },
      { tick:5, agent_id:'gate_agent', action:'conflict_raised', detail:'Conflict CON-001: No wide-body gate available for AI603 arriving T+45. G5 occupied by G8505, G8 unavailable. Raising to Orchestrator.', affected_flights:['G8505','AI603'] },
      { tick:5, agent_id:'orchestrator', action:'conflict_raised', detail:'Conflict CON-001 registered. Analyzing weather disruption impact on 5 affected flights — will prioritize departure sequence to free G5 for AI603 if turnaround completes in time.', affected_flights:['AI101','AI102','UK303','SG404','G8505','AI603'] },
    ],
  },

  // === TICK 10: Orchestrator actively resolving, conflicts being resolved ===
  {
    current_tick: 10,
    flights: {
      'AI101': { flight_id:'AI101', airline:'Air India', aircraft_type:'WIDE_BODY', scheduled_arrival:t(0), scheduled_departure:t(90), actual_arrival:t(2), actual_departure:null, status:'AT_GATE', assigned_gate:'G1', assigned_crew:['C001','C002','C003'], turnaround_time:90, is_delayed:true },
      'AI102': { flight_id:'AI102', airline:'Air India', aircraft_type:'NARROW_BODY', scheduled_arrival:t(2), scheduled_departure:t(52), actual_arrival:t(5), actual_departure:null, status:'AT_GATE', assigned_gate:'G2', assigned_crew:['C004','C005','C006'], turnaround_time:45, is_delayed:true },
      'UK303': { flight_id:'UK303', airline:'Vistara', aircraft_type:'NARROW_BODY', scheduled_arrival:t(5), scheduled_departure:t(55), actual_arrival:t(5), actual_departure:null, status:'READY_FOR_PUSHBACK', assigned_gate:'G3', assigned_crew:['C007','C008'], turnaround_time:45, is_delayed:false },
      'SG404': { flight_id:'SG404', airline:'SpiceJet', aircraft_type:'NARROW_BODY', scheduled_arrival:t(8), scheduled_departure:t(58), actual_arrival:t(9), actual_departure:null, status:'AT_GATE', assigned_gate:'G4', assigned_crew:['C009','C010'], turnaround_time:40, is_delayed:true },
      'G8505': { flight_id:'G8505', airline:'GoFirst', aircraft_type:'NARROW_BODY', scheduled_arrival:t(10), scheduled_departure:t(60), actual_arrival:t(11), actual_departure:null, status:'AT_GATE', assigned_gate:'G5', assigned_crew:['C011','C012'], turnaround_time:40, is_delayed:false },
      'AI603': { flight_id:'AI603', airline:'Air India Express', aircraft_type:'WIDE_BODY', scheduled_arrival:t(45), scheduled_departure:t(145), actual_arrival:null, actual_departure:null, status:'SCHEDULED', assigned_gate:null, assigned_crew:[], turnaround_time:95, is_delayed:false },
      'IX700': { flight_id:'IX700', airline:'Air India Express', aircraft_type:'NARROW_BODY', scheduled_arrival:t(60), scheduled_departure:t(110), actual_arrival:null, actual_departure:null, status:'SCHEDULED', assigned_gate:null, assigned_crew:[], turnaround_time:45, is_delayed:false },
      '6E801': { flight_id:'6E801', airline:'IndiGo', aircraft_type:'NARROW_BODY', scheduled_arrival:t(30), scheduled_departure:t(75), actual_arrival:null, actual_departure:null, status:'IN_AIR', assigned_gate:null, assigned_crew:[], turnaround_time:42, is_delayed:false },
      '6E802': { flight_id:'6E802', airline:'IndiGo', aircraft_type:'NARROW_BODY', scheduled_arrival:t(35), scheduled_departure:t(80), actual_arrival:null, actual_departure:null, status:'IN_AIR', assigned_gate:null, assigned_crew:[], turnaround_time:42, is_delayed:false },
      'QP901': { flight_id:'QP901', airline:'Akasa Air', aircraft_type:'NARROW_BODY', scheduled_arrival:t(55), scheduled_departure:t(100), actual_arrival:null, actual_departure:null, status:'SCHEDULED', assigned_gate:null, assigned_crew:[], turnaround_time:38, is_delayed:false },
    },
    gates: {
      'G1': { gate_id:'G1', supports_wide_body:true,  gate_status:'OCCUPIED',   assigned_flight:'AI101' },
      'G2': { gate_id:'G2', supports_wide_body:false, gate_status:'OCCUPIED',   assigned_flight:'AI102' },
      'G3': { gate_id:'G3', supports_wide_body:false, gate_status:'OCCUPIED',   assigned_flight:'UK303' },
      'G4': { gate_id:'G4', supports_wide_body:false, gate_status:'OCCUPIED',   assigned_flight:'SG404' },
      'G5': { gate_id:'G5', supports_wide_body:true,  gate_status:'OCCUPIED',   assigned_flight:'G8505' },
      'G6': { gate_id:'G6', supports_wide_body:false, gate_status:'OPEN',       assigned_flight:null },
      'G7': { gate_id:'G7', supports_wide_body:false, gate_status:'OPEN',       assigned_flight:null },
      'G8': { gate_id:'G8', supports_wide_body:true,  gate_status:'UNAVAILABLE',assigned_flight:null },
      'G9': { gate_id:'G9', supports_wide_body:false, gate_status:'OPEN',       assigned_flight:null },
      'G10':{ gate_id:'G10',supports_wide_body:false, gate_status:'OPEN',       assigned_flight:null },
    },
    crew: {
      'C001':{ crew_id:'C001', role:'BAGGAGE',  available:false, assigned_flight:'AI101', shift_minutes_remaining:340 },
      'C002':{ crew_id:'C002', role:'PUSHBACK', available:false, assigned_flight:'AI101', shift_minutes_remaining:300 },
      'C003':{ crew_id:'C003', role:'CLEANING', available:false, assigned_flight:'AI101', shift_minutes_remaining:270 },
      'C004':{ crew_id:'C004', role:'BAGGAGE',  available:false, assigned_flight:'AI102', shift_minutes_remaining:390 },
      'C005':{ crew_id:'C005', role:'PUSHBACK', available:false, assigned_flight:'AI102', shift_minutes_remaining:360 },
      'C006':{ crew_id:'C006', role:'CLEANING', available:false, assigned_flight:'AI102', shift_minutes_remaining:320 },
      'C007':{ crew_id:'C007', role:'BAGGAGE',  available:false, assigned_flight:'UK303', shift_minutes_remaining:320 },
      'C008':{ crew_id:'C008', role:'PUSHBACK', available:false, assigned_flight:'UK303', shift_minutes_remaining:440 },
      'C009':{ crew_id:'C009', role:'CLEANING', available:false, assigned_flight:'SG404', shift_minutes_remaining:420 },
      'C010':{ crew_id:'C010', role:'BAGGAGE',  available:false, assigned_flight:'SG404', shift_minutes_remaining:480 },
      'C011':{ crew_id:'C011', role:'PUSHBACK', available:false, assigned_flight:'G8505', shift_minutes_remaining:370 },
      'C012':{ crew_id:'C012', role:'CLEANING', available:false, assigned_flight:'G8505', shift_minutes_remaining:330 },
    },
    open_disruptions: [
      {
        event_id: 'DIS-WEATHER-001',
        disruption_type: 'WEATHER',
        trigger_time: t(25),
        severity: 4,
        disruption_description: 'Severe thunderstorm cell moving through approach corridor. Wind shear on 27L. All inbound traffic on holding pattern. Extended turnaround expected for gates G1–G5.',
        affected_flights: ['AI101','AI102','UK303','SG404','G8505'],
        resolved: false,
      }
    ],
    open_conflicts: [
      {
        conflict_id: 'CON-001',
        agent_id: 'gate_agent',
        conflict_description: 'Wide-body gate conflict: G5 occupied by G8505, G8 UNAVAILABLE. AI603 (Wide Body, T+45) requires wide-body gate. Orchestrator prioritizing UK303 departure to free G3 for reassignment workaround.',
        resolved: false,
        affected_flights: ['G8505','AI603'],
      }
    ],
    decision_log: [
      { tick:0, agent_id:'gate_agent', action:'gate_assignment', detail:'Assigned AI101 (Wide Body) to Gate G1.', affected_flights:['AI101'] },
      { tick:0, agent_id:'gate_agent', action:'gate_assignment', detail:'Assigned AI102 to Gate G2.', affected_flights:['AI102'] },
      { tick:0, agent_id:'gate_agent', action:'gate_assignment', detail:'Assigned UK303 to Gate G3.', affected_flights:['UK303'] },
      { tick:0, agent_id:'crew_agent', action:'crew_assignment', detail:'Assigned crew C001, C002, C003 to AI101.', affected_flights:['AI101'] },
      { tick:0, agent_id:'crew_agent', action:'crew_assignment', detail:'Assigned crew C004, C005, C006 to AI102.', affected_flights:['AI102'] },
      { tick:0, agent_id:'ats_agent', action:'delay_flag', detail:'AI102 actual arrival +3 min — flagged as delayed.', affected_flights:['AI102'] },
      { tick:5, agent_id:'gate_agent', action:'gate_assignment', detail:'Assigned SG404 to Gate G4.', affected_flights:['SG404'] },
      { tick:5, agent_id:'gate_agent', action:'gate_assignment', detail:'Assigned G8505 to Gate G5 — wide-body capacity now exhausted (G8 unavailable).', affected_flights:['G8505'] },
      { tick:5, agent_id:'disruption_agent', action:'disruption_triggered', detail:'🌩 DIS-WEATHER-001 INJECTED — Severity LEVEL_4 thunderstorm. 5 flights affected. Escalating to Orchestrator.', affected_flights:['AI101','AI102','UK303','SG404','G8505'] },
      { tick:5, agent_id:'gate_agent', action:'conflict_raised', detail:'Conflict CON-001: No wide-body gate for AI603 (T+45). Raising to Orchestrator.', affected_flights:['G8505','AI603'] },
      { tick:5, agent_id:'orchestrator', action:'conflict_raised', detail:'CON-001 registered. Analyzing disruption impact — prioritizing departure sequence to free gate capacity.', affected_flights:['AI101','AI102','UK303','SG404','G8505','AI603'] },
      { tick:10, agent_id:'ats_agent', action:'delay_flag', detail:'Weather holding pattern extends estimated departure delays: AI102 +18min, SG404 +22min, AI101 departure window at risk if storm persists beyond T+40.', affected_flights:['AI101','AI102','SG404'] },
      { tick:10, agent_id:'orchestrator', action:'conflict_resolution', detail:'Conflict resolution strategy: expedite UK303 pushback (READY_FOR_PUSHBACK) to vacate G3. Reassign C008 to UK303 Pushback immediately. This frees G3 at T+12 for 6E801 (narrowbody, T+30).', affected_flights:['UK303','6E801'] },
      { tick:10, agent_id:'crew_agent', action:'crew_reassigned', detail:'Crew C008 (Pushback) reassigned from SG404 standby to UK303 per Orchestrator directive — UK303 now has full pushback crew.', affected_flights:['UK303','SG404'] },
      { tick:10, agent_id:'disruption_agent', action:'disruption_escalated', detail:'DIS-WEATHER-001 still unresolved — re-escalating. Storm cell tracking suggests clearance in ~20 min. Recommend holding AI603 at current schedule; G5 should be free post G8505 departure.', affected_flights:['AI101','AI102','UK303','SG404','G8505'] },
    ],
  },

  // === TICK 15: Disruption partially resolved, AI603 gets a gate ===
  {
    current_tick: 15,
    flights: {
      'AI101': { flight_id:'AI101', airline:'Air India', aircraft_type:'WIDE_BODY', scheduled_arrival:t(0), scheduled_departure:t(90), actual_arrival:t(2), actual_departure:null, status:'AT_GATE', assigned_gate:'G1', assigned_crew:['C001','C002','C003'], turnaround_time:90, is_delayed:true },
      'AI102': { flight_id:'AI102', airline:'Air India', aircraft_type:'NARROW_BODY', scheduled_arrival:t(2), scheduled_departure:t(52), actual_arrival:t(5), actual_departure:null, status:'READY_FOR_PUSHBACK', assigned_gate:'G2', assigned_crew:['C004','C005','C006'], turnaround_time:45, is_delayed:true },
      'UK303': { flight_id:'UK303', airline:'Vistara', aircraft_type:'NARROW_BODY', scheduled_arrival:t(5), scheduled_departure:t(55), actual_arrival:t(5), actual_departure:t(57), status:'DEPARTED', assigned_gate:null, assigned_crew:[], turnaround_time:45, is_delayed:false },
      'SG404': { flight_id:'SG404', airline:'SpiceJet', aircraft_type:'NARROW_BODY', scheduled_arrival:t(8), scheduled_departure:t(58), actual_arrival:t(9), actual_departure:null, status:'AT_GATE', assigned_gate:'G4', assigned_crew:['C009','C010'], turnaround_time:40, is_delayed:true },
      'G8505': { flight_id:'G8505', airline:'GoFirst', aircraft_type:'NARROW_BODY', scheduled_arrival:t(10), scheduled_departure:t(60), actual_arrival:t(11), actual_departure:null, status:'READY_FOR_PUSHBACK', assigned_gate:'G5', assigned_crew:['C011','C012'], turnaround_time:40, is_delayed:false },
      'AI603': { flight_id:'AI603', airline:'Air India Express', aircraft_type:'WIDE_BODY', scheduled_arrival:t(45), scheduled_departure:t(145), actual_arrival:null, actual_departure:null, status:'IN_AIR', assigned_gate:'G5', assigned_crew:[], turnaround_time:95, is_delayed:false },
      'IX700': { flight_id:'IX700', airline:'Air India Express', aircraft_type:'NARROW_BODY', scheduled_arrival:t(60), scheduled_departure:t(110), actual_arrival:null, actual_departure:null, status:'SCHEDULED', assigned_gate:null, assigned_crew:[], turnaround_time:45, is_delayed:false },
      '6E801': { flight_id:'6E801', airline:'IndiGo', aircraft_type:'NARROW_BODY', scheduled_arrival:t(30), scheduled_departure:t(75), actual_arrival:null, actual_departure:null, status:'IN_AIR', assigned_gate:'G3', assigned_crew:[], turnaround_time:42, is_delayed:false },
      '6E802': { flight_id:'6E802', airline:'IndiGo', aircraft_type:'NARROW_BODY', scheduled_arrival:t(35), scheduled_departure:t(80), actual_arrival:null, actual_departure:null, status:'IN_AIR', assigned_gate:null, assigned_crew:[], turnaround_time:42, is_delayed:false },
      'QP901': { flight_id:'QP901', airline:'Akasa Air', aircraft_type:'NARROW_BODY', scheduled_arrival:t(55), scheduled_departure:t(100), actual_arrival:null, actual_departure:null, status:'SCHEDULED', assigned_gate:null, assigned_crew:[], turnaround_time:38, is_delayed:false },
    },
    gates: {
      'G1': { gate_id:'G1', supports_wide_body:true,  gate_status:'OCCUPIED',   assigned_flight:'AI101' },
      'G2': { gate_id:'G2', supports_wide_body:false, gate_status:'OCCUPIED',   assigned_flight:'AI102' },
      'G3': { gate_id:'G3', supports_wide_body:false, gate_status:'OPEN',       assigned_flight:null },
      'G4': { gate_id:'G4', supports_wide_body:false, gate_status:'OCCUPIED',   assigned_flight:'SG404' },
      'G5': { gate_id:'G5', supports_wide_body:true,  gate_status:'OCCUPIED',   assigned_flight:'G8505' },
      'G6': { gate_id:'G6', supports_wide_body:false, gate_status:'OPEN',       assigned_flight:null },
      'G7': { gate_id:'G7', supports_wide_body:false, gate_status:'OPEN',       assigned_flight:null },
      'G8': { gate_id:'G8', supports_wide_body:true,  gate_status:'UNAVAILABLE',assigned_flight:null },
      'G9': { gate_id:'G9', supports_wide_body:false, gate_status:'OPEN',       assigned_flight:null },
      'G10':{ gate_id:'G10',supports_wide_body:false, gate_status:'OPEN',       assigned_flight:null },
    },
    crew: {
      'C001':{ crew_id:'C001', role:'BAGGAGE',  available:false, assigned_flight:'AI101', shift_minutes_remaining:325 },
      'C002':{ crew_id:'C002', role:'PUSHBACK', available:false, assigned_flight:'AI101', shift_minutes_remaining:285 },
      'C003':{ crew_id:'C003', role:'CLEANING', available:false, assigned_flight:'AI101', shift_minutes_remaining:255 },
      'C004':{ crew_id:'C004', role:'BAGGAGE',  available:false, assigned_flight:'AI102', shift_minutes_remaining:375 },
      'C005':{ crew_id:'C005', role:'PUSHBACK', available:false, assigned_flight:'AI102', shift_minutes_remaining:345 },
      'C006':{ crew_id:'C006', role:'CLEANING', available:false, assigned_flight:'AI102', shift_minutes_remaining:305 },
      'C007':{ crew_id:'C007', role:'BAGGAGE',  available:true,  assigned_flight:null, shift_minutes_remaining:305 },
      'C008':{ crew_id:'C008', role:'PUSHBACK', available:true,  assigned_flight:null, shift_minutes_remaining:425 },
      'C009':{ crew_id:'C009', role:'CLEANING', available:false, assigned_flight:'SG404', shift_minutes_remaining:405 },
      'C010':{ crew_id:'C010', role:'BAGGAGE',  available:false, assigned_flight:'SG404', shift_minutes_remaining:465 },
      'C011':{ crew_id:'C011', role:'PUSHBACK', available:false, assigned_flight:'G8505', shift_minutes_remaining:355 },
      'C012':{ crew_id:'C012', role:'CLEANING', available:false, assigned_flight:'G8505', shift_minutes_remaining:315 },
    },
    open_disruptions: [
      {
        event_id: 'DIS-WEATHER-001',
        disruption_type: 'WEATHER',
        trigger_time: t(25),
        severity: 4,
        disruption_description: 'Thunderstorm cell tracking north — approach corridor expected to clear in ~5 min. Inbound flights resuming approach. Gates G1–G4 still under extended turnaround protocol.',
        affected_flights: ['AI101','AI102','SG404'],
        resolved: false,
      }
    ],
    open_conflicts: [
      {
        conflict_id: 'CON-001',
        agent_id: 'gate_agent',
        conflict_description: 'RESOLVED: AI603 pre-assigned to G5 (pending G8505 departure). G8505 is READY_FOR_PUSHBACK — gate will be available before AI603 arrival at T+45. Conflict closed.',
        resolved: true,
        affected_flights: ['G8505','AI603'],
      }
    ],
    decision_log: [
      { tick:0, agent_id:'gate_agent', action:'gate_assignment', detail:'Assigned AI101 (Wide Body) to Gate G1.', affected_flights:['AI101'] },
      { tick:0, agent_id:'gate_agent', action:'gate_assignment', detail:'Assigned AI102 to Gate G2.', affected_flights:['AI102'] },
      { tick:0, agent_id:'gate_agent', action:'gate_assignment', detail:'Assigned UK303 to Gate G3.', affected_flights:['UK303'] },
      { tick:0, agent_id:'crew_agent', action:'crew_assignment', detail:'Assigned crew C001, C002, C003 to AI101.', affected_flights:['AI101'] },
      { tick:0, agent_id:'crew_agent', action:'crew_assignment', detail:'Assigned crew C004, C005, C006 to AI102.', affected_flights:['AI102'] },
      { tick:0, agent_id:'ats_agent', action:'delay_flag', detail:'AI102 actual arrival +3 min — flagged as delayed.', affected_flights:['AI102'] },
      { tick:5, agent_id:'gate_agent', action:'gate_assignment', detail:'Assigned SG404 to Gate G4.', affected_flights:['SG404'] },
      { tick:5, agent_id:'gate_agent', action:'gate_assignment', detail:'Assigned G8505 to Gate G5 — wide-body capacity exhausted (G8 unavailable).', affected_flights:['G8505'] },
      { tick:5, agent_id:'disruption_agent', action:'disruption_triggered', detail:'🌩 DIS-WEATHER-001 INJECTED — Severity LEVEL_4 thunderstorm. 5 flights affected. Escalating to Orchestrator.', affected_flights:['AI101','AI102','UK303','SG404','G8505'] },
      { tick:5, agent_id:'gate_agent', action:'conflict_raised', detail:'Conflict CON-001: No wide-body gate for AI603 (T+45). Raising to Orchestrator.', affected_flights:['G8505','AI603'] },
      { tick:5, agent_id:'orchestrator', action:'conflict_raised', detail:'CON-001 registered. Analyzing disruption impact on 5 flights — prioritizing departure sequence.', affected_flights:['AI101','AI102','UK303','SG404','G8505','AI603'] },
      { tick:10, agent_id:'ats_agent', action:'delay_flag', detail:'Weather delays: AI102 +18min, SG404 +22min. AI101 departure window at risk.', affected_flights:['AI101','AI102','SG404'] },
      { tick:10, agent_id:'orchestrator', action:'conflict_resolution', detail:'Expediting UK303 pushback — freed G3 at T+12 for 6E801 (arriving T+30). C008 reassigned to UK303 Pushback.', affected_flights:['UK303','6E801'] },
      { tick:10, agent_id:'crew_agent', action:'crew_reassigned', detail:'Crew C008 (Pushback) reassigned from SG404 standby to UK303 per Orchestrator directive.', affected_flights:['UK303','SG404'] },
      { tick:10, agent_id:'disruption_agent', action:'disruption_escalated', detail:'DIS-WEATHER-001 re-escalating. Storm tracking suggests clearance in ~20 min. AI603 can hold schedule.', affected_flights:['AI101','AI102','UK303','SG404','G8505'] },
      { tick:15, agent_id:'gate_agent', action:'gate_assignment', detail:'Pre-assigned G5 to AI603 — G8505 READY_FOR_PUSHBACK, gate free before T+45. CON-001 resolved.', affected_flights:['AI603','G8505'] },
      { tick:15, agent_id:'orchestrator', action:'conflict_resolved', detail:'✅ CON-001 RESOLVED — AI603 gate secured. UK303 departed T+57. G3 now available for 6E801 inbound.', affected_flights:['AI603','UK303','6E801'] },
      { tick:15, agent_id:'gate_agent', action:'gate_assignment', detail:'Pre-assigned G3 to 6E801 (IndiGo, arriving T+30). Gate confirmed available.', affected_flights:['6E801'] },
      { tick:15, agent_id:'ats_agent', action:'schedule_update', detail:'Storm corridor clearing — AI102 and SG404 delay risk downgraded. AI102 departure window T+70 (was T+52), SG404 T+75 (was T+58). Updated schedule propagated.', affected_flights:['AI102','SG404'] },
    ],
  },
];
