const fs = require('fs');
const path = require('path');

const walk = (dir) => {
  let results = [];
  const list = fs.readdirSync(dir);
  list.forEach(file => {
    const full = path.join(dir, file);
    const stat = fs.statSync(full);
    if (stat && stat.isDirectory()) {
      results = results.concat(walk(full));
    } else if (file.endsWith('.jsx')) {
      results.push(full);
    }
  });
  return results;
};

const files = walk(__dirname);
let cssClasses = new Set();
let cssMap = {};

function getClassNameForStyle(styleStr) {
  const normalized = styleStr.replace(/\s+/g, ' ').trim();
  
  if (normalized.includes("padding: '2px 6px', fontSize: '0.7rem'")) return "btn-sm";
  if (normalized.includes("height: '100%'")) return "panel-full-height";
  if (normalized.includes("display: 'flex', alignItems: 'center', gap: '8px'")) return "flex-center-gap";
  if (normalized.includes("background: 'var(--gate-open)'")) return "bg-gate-open";
  if (normalized.includes("background: 'var(--gate-occupied)'")) return "bg-gate-occupied";
  if (normalized.includes("background: 'var(--gate-unavail)'")) return "bg-gate-unavail";
  if (normalized.includes("background: 'var(--sev-1)'")) return "bg-sev-1";
  if (normalized.includes("background: 'var(--sev-2)'")) return "bg-sev-2";
  if (normalized.includes("background: 'var(--sev-3)'")) return "bg-sev-3";
  if (normalized.includes("background: 'var(--sev-4)'")) return "bg-sev-4";
  if (normalized.includes("background: 'var(--sev-5)'")) return "bg-sev-5";
  if (normalized.includes("background: 'var(--agent-disruption)'")) return "bg-agent-disruption";
  if (normalized.includes("background: 'var(--status-landed)'")) return "bg-status-landed";
  if (normalized.includes("background: 'var(--status-scheduled)'")) return "bg-status-scheduled";
  if (normalized.includes("background: 'var(--status-in-air)'")) return "bg-status-in-air";
  if (normalized.includes("background: 'var(--status-at-gate)'")) return "bg-status-at-gate";
  if (normalized.includes("background: 'var(--status-pushback)'")) return "bg-status-pushback";
  if (normalized.includes("background: 'var(--status-departed)'")) return "bg-status-departed";
  if (normalized.includes("background: 'var(--status-cancelled)'")) return "bg-status-cancelled";
  if (normalized.includes("display: 'flex', flexDirection: 'column', gap: '4px'")) return "flex-col-gap-4";
  if (normalized.includes("display: 'flex', flexDirection: 'column', height: '100%', minHeight: 0")) return "flex-col-full";
  if (normalized.includes("display: 'flex', gap: 5")) return "flex-gap-sm";
  
  return null;
}

files.forEach(file => {
  let content = fs.readFileSync(file, 'utf8');
  let modified = false;
  
  const regex = /style=\{\{\s*([^}]+)\s*\}\}/g;
  content = content.replace(regex, (match, inner) => {
    if (inner.includes('cfg.color') || inner.includes('pct') || inner.includes('cfg.soft') || inner.includes('cfg.fillStyle')) {
      return match;
    }
    
    const cname = getClassNameForStyle(inner);
    if (cname) {
      modified = true;
      cssClasses.add(cname);
      return `className="${cname}"`;
    }
    return match;
  });
  
  const mergeRegex = /className="([^"]+)"\s+className="([^"]+)"/g;
  while (mergeRegex.test(content)) {
    content = content.replace(mergeRegex, 'className="$1 $2"');
  }

  if (modified) {
    fs.writeFileSync(file, content, 'utf8');
    console.log("Updated", file);
  }
});

let cssToAppend = "\n/* AUTOGENERATED UTILITIES FROM MIGRATION */\n";
cssToAppend += ".panel-full-height { height: 100%; }\n";
cssToAppend += ".flex-center-gap { display: flex; align-items: center; gap: var(--gap-sm); }\n";
cssToAppend += ".flex-gap-sm { display: flex; gap: 5px; }\n";
cssToAppend += ".flex-col-gap-4 { display: flex; flex-direction: column; gap: var(--gap-xs); }\n";
cssToAppend += ".flex-col-full { display: flex; flex-direction: column; height: 100%; min-height: 0; }\n";
['gate-open', 'gate-occupied', 'gate-unavail', 'sev-1', 'sev-2', 'sev-3', 'sev-4', 'sev-5', 'agent-disruption', 'status-landed', 'status-scheduled', 'status-in-air', 'status-at-gate', 'status-pushback', 'status-departed', 'status-cancelled'].forEach(k => {
  cssToAppend += `.bg-${k} { background: var(--${k}); }\n`;
});

fs.appendFileSync(path.join(__dirname, 'index.css'), cssToAppend);
console.log("Added CSS classes to index.css");
